name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: g++ decrypt.cpp
    - name: Upload
      uses: actions/upload-artifact@v2.2.2
      with:
          name: "decrypt.exe"
          path: "/"
