name: C/C++ CI

on:
   workflow_dispatch
jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: g++ decrypt.cpp
    - name: Upload
      uses: actions/upload-artifact@v2.2.2
      with:
          name: "decrypt.exe"
          path: "/decrypt.exe"
